apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: caddy
  name: caddy-public
spec:
  externalIPs:
    - INSERT_YOUR_PUBLIC_IP
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 31180
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 31443
  selector:
    io.kompose.service: caddy
  type: NodePort