apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rtmp
  name: rtmp-public
spec:
  externalIPs:
    - INSERT_YOUR_PUBLIC_IP
  ports:
    - name: "1935"
      port: 1935
      nodePort: 31935
      targetPort: 1935
  selector:
    io.kompose.service: rtmp
  type: NodePort